language: objective-c
osx_image: xcode10

install:
  - cd ./RxBus-Demo; pod install

matrix:
  include:
    - env: JOB="XCODE" DEST="OS=12.0,name=iPhone X" SCHEME="RxBus-Demo-iOS" SDK="iphonesimulator" ACTION="test"
      osx_image: xcode10
    - env: JOB="XCODE" DEST="arch=x86_64" SCHEME="RxBus-Demo-macOS" SDK="macosx" ACTION="test"
      osx_image: xcode10
    - env: JOB="XCODE" DEST="OS=11.0,name=Apple TV 4K" SCHEME="RxBus-Demo-tvOS" SDK="appletvsimulator" ACTION="test"
      osx_image: xcode10
    - env: JOB="XCODE" DEST="OS=4.0,name=Apple Watch - 42mm" SCHEME="RxBus-Demo-watchOS" SDK="watchsimulator" ACTION="build"
      osx_image: xcode10

script:
  - set -o pipefail
  - xcodebuild "$ACTION" -workspace WKJavaScriptController-Demo.xcodeproj/project.xcworkspace -scheme "$SCHEME" -sdk "$SDK" -destination "$DEST" -configuration Release ENABLE_TESTABILITY=YES | xcpretty

notifications:
  email: false
  slack:
    rooms:
      - 'rididev:KMm0EBQYY1ThicCJo0CwYb5U'
    on_success: change
